### ISSUE TITLE
师傅，使用fofa 提取资产的时候是不是有问题呀，

### ISSUE THREAD

**Issue by NewBieLD** [lemonlove7/EHole_magic#1]
我-f或者-s 后没有具体资产显示
token值也配了

**Comment by lemonlove7** [comment]
可以用呀，是不是你的key失效了或者每日用量达到上限了
<img width="721" alt="image" src="https://github.com/lemonlove7/EHole_magic/assets/56328995/e24bbf93-1ffa-466f-a889-91b875d49d69">

**Comment by NewBieLD** [comment]
没有呀，用fofa viewer正常的

**Comment by lemonlove7** [comment]
> 没有呀，用fofaviewer正常的

修复了，下载最新版即可

**Comment by liquO0o** [comment]
> > 没有呀，用fofaviewer正常的
> 
> 修复了，下载最新版即可

想问下默认提取fofa多少页呀

**Comment by NewBieLD** [comment]
@lemonlove7   <裂开了>师傅， windows下一直没成功，换了设备也是没有结果，是我配置有问题吗？
![image](https://github.com/lemonlove7/EHole_magic/assets/111514900/9c2afba3-57e5-4100-867b-98523cc10879)
![image](https://github.com/lemonlove7/EHole_magic/assets/111514900/4e49e908-1f11-4a54-a098-e313453d69d4)

**Comment by lemonlove7** [comment]
下载最新版，语句外面加俩个'号

**Comment by NewBieLD** [comment]
好的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月30日(周三) 上午9:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lemonlove7/EHole_magic] 师傅，使用fofa 提取资产的时候是不是有问题呀， (Issue #1)




 
下载最新版，语句外面加俩个'号

**Comment by Fat-bear** [comment]
![image](https://github.com/lemonlove7/EHole_magic/assets/23469762/0958ac52-2197-46c9-abdb-fb758d7ccaa9)

**Comment by lemonlove7** [comment]
你这个是没ftp这个模块 ，直接下载可执行文件就行
