### ISSUE TITLE
接口好像变了，无法查询了

### ISSUE THREAD

**Issue by sdfdfasd12** [lemonlove7/EHole_magic#16]
![image](https://github.com/lemonlove7/EHole_magic/assets/144324900/29e677a2-80fa-45c5-a3aa-48b0b5bb9a9b)

**Comment by sdfdfasd12** [comment]
![image](https://github.com/lemonlove7/EHole_magic/assets/144324900/a5085a7b-12c3-41d1-b727-d6762e0f7dc9)

**Comment by lemonlove7** [comment]
<img width="1426" alt="image" src="https://github.com/lemonlove7/EHole_magic/assets/56328995/b9247498-74ab-4ff3-84bf-bce406baf1e7">
你网络的原因吧
