### ISSUE TITLE
fofa的api的url可以改为自定义的嘛？

### ISSUE THREAD

**Issue by NSQAQ** [lemonlove7/EHole_magic#21]

**Comment by lemonlove7** [comment]
fofa的接口不能用了吗？

**Comment by NSQAQ** [comment]
可以使用，但是如果想fofaview那样可以自定义api就好了。因为，有时候使用fofa不一定是fofa.info。例如：

**Comment by NSQAQ** [comment]
![QQ截图20240306163944](https://github.com/lemonlove7/EHole_magic/assets/41403864/fb20ba18-1874-4344-af90-f2a0e66d8adf)

**Comment by yz1639** [comment]
冒昧的问一句，fofa.info 和fofa.red 换不换有啥区别吗

**Comment by NSQAQ** [comment]
> 冒昧的问一句区别，fofa.info 和 fofa.red 换不换有啥吗

一个是官方的api接口，另一个是私人的接口。emm，其实也无所谓。自己下源码然后自己改也是可以的。

**Comment by yz1639** [comment]
源码跟Releases好像不是同步的🤔
