### ISSUE TITLE
师傅请问没有结果及过程是因为fofa没有会员吗

### ISSUE THREAD

**Issue by F1oww** [lemonlove7/EHole_magic#23]
<img width="570" alt="截屏2024-04-02 15 35 27" src="https://github.com/lemonlove7/EHole_magic/assets/97645118/44e90810-f423-471e-9b26-643a6c145fde">

**Comment by lemonlove7** [comment]
我记得普通注册用户用不了fofa api吧

**Comment by F1oww** [comment]
谢谢师傅，我看了一下fofa接口文档 非会员确实不能使用api
