### ISSUE TITLE
最新版也没有fofa显示啊 师傅

### ISSUE THREAD

**Issue by wangzaixiaoyu** [lemonlove7/EHole_magic#5]
最新版也没有fofa显示啊 师傅

**Comment by lemonlove7** [comment]
你配置的问题吧
<img width="700" alt="image" src="https://github.com/lemonlove7/EHole_magic/assets/56328995/22f4b8f3-0d49-4da7-8597-170bb772d2a3">

**Comment by lemonlove7** [comment]
299的是最新的

**Comment by lemonlove7** [comment]
如果不行，加俩个'号
<img width="998" alt="image" src="https://github.com/lemonlove7/EHole_magic/assets/56328995/ea83806a-a10b-4ba6-ba71-b547979aeced">
