### ISSUE TITLE
cookie造成的bug

### ISSUE THREAD

**Issue by X1SP** [lemonlove7/EHole_magic#8]
module/finger/http.go中httprequest()默认对所有请求都添加rememberme这个cookie
但是对于一些CMS（这里用大华做得测试）会报错
![image](https://github.com/lemonlove7/EHole_magic/assets/30949893/8dc35dd9-c4e4-4737-a881-fcbf795e2bf1)
我现在暂时的解决方法是给httprequest()加了个flag参数，用来决定是否添加rememberme这个cookie（上图中的if flag判断）
然后在module/finger/finger.go的fingerScan()中对于error的再做一次不带rememberme的请求
![image](https://github.com/lemonlove7/EHole_magic/assets/30949893/46e9d7cc-a904-4887-b738-1954039a9785)
有空的话师傅可以debug一下，改优雅点儿

**Comment by X1SP** [comment]
付一个大华的测试案例
![image](https://github.com/lemonlove7/EHole_magic/assets/30949893/c36eb2be-22e2-4095-8819-14adb8fa80df)

**Comment by X1SP** [comment]
附一个大华的测试案例
![image](https://github.com/lemonlove7/EHole_magic/assets/30949893/1f3ff501-5a5f-4dbb-be64-6696eb2d302a)

**Comment by lemonlove7** [comment]
师傅强的呀
