### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by komomon** [lemonlove7/EHole_magic#9]
1 对于指纹识别，是增加了header title这俩关键词吗，还有其他的吗，可以对新增的指纹规则这块readme，介绍一下吗，方便自己添加
2 只支持识别web http服务的指纹是吗
3 指纹匹配支持正则吗

**Comment by lemonlove7** [comment]
1、支持header title 指纹文件里有
2、只加了ftp，后面问了其他师傅，觉得没必要加，加上那有点类似于fscan了。
3、匹配关键字和图标hash
